language: node_js

node_js:
- '5'

before_install: openssl aes-256-cbc -K $encrypted_046c388bf68a_key -iv $encrypted_046c388bf68a_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d

before_script:
- npm install -g bower
- bower install

notifications:
  slack:
    secure: frwYvR/nXTR+dO73WU2dQdXdiMJ/XulVy2q9hbxAv4ONgUtR719JQXmweEObWvd4GpiZU/ZsOYlb5thwt7GHQtWzO5LNlSvIYlzl7s3sofs/ZbhZ9RmNzCfrzbik6GQSLCLh/bibGj1fv1xntpm32WUQ22qESbi1lhxW/B9+hDY=

addons:
  code_climate:
    secure: DjBknUGwz5cKdD7RaAInJZd4HNGuDk8k+u36y8nRLieWgRvTMEa3w4OzXI71y+eSaO3cgUAsPXP3wgzjuOh7CTS/V9RrsrBj/PFufzqA0ro9b78TZUdbyPTHe2CrvohpEUZkv3n9/U50JGZT3V6sf6mzKoJ8kDiro60Ja0eLkws=

after_script:
- cat lcov.info | codeclimate

sudo: false

deploy:
  # - provider: releases
  #   api_key:
  #     secure: UK/BK5UavwiWJjFNhkkj7Az+MeyXAUvi9uMthyanfcxKSgc9OUnLiAH3BehLeZWeTEmrbqBh5nwbS1M1Ly+Kw6rUajM4u59YyBqeQlJlZR2rNtpTut1q1S6/SYMJe2OCrXeJzgU0YRHgZhgLazTFCcUzxQddz/hxsj4yQa6NtnI=
  #   file: dist/**/*
  #   skip_cleanup: true
  #   on:
  #     tags: true
  #     repo: podlove/podlove-web-player
  - provider: script
    script: .travis/deploy.sh $TRAVIS_TAG
    on:
      tags: true
      repo: podlove/podlove-web-player
